"""initial schema

Revision ID: 66f746db30bb
Revises: 
Create Date: 2026-08-28 10:25:53.042200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '66f746db30bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifactrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('user',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workspace',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authsession',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['organization_slug'], ['organization.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['organization_slug'], ['organization.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipelinerun',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('workspace_id', sa.CHAR(length=36), nullable=False),
    sa.Column('preset', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.CHAR(length=8), nullable=False),
    sa.Column('max_records', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_step_index', sa.SmallInteger(), nullable=False),
    sa.Column('cancel_flag', sa.Boolean(), nullable=False),
    sa.Column('steps_json', sa.JSON(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('report_blob_path', sa.String(length=256), nullable=True),
    sa.Column('pico_csv_blob_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('max_records >= 1 AND max_records <= 2500', name='cc_pipelinerun_max_records'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelinerun_preset'), 'pipelinerun', ['preset'], unique=False)
    op.create_index(op.f('ix_pipelinerun_status'), 'pipelinerun', ['status'], unique=False)
    op.create_index(op.f('ix_pipelinerun_workspace_id'), 'pipelinerun', ['workspace_id'], unique=False)
    op.create_table('researchproject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prisma_override_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organization_slug'], ['organization.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dedupdiagnostic',
    sa.Column('run_id', sa.CHAR(length=32), nullable=False),
    sa.Column('step_idx', sa.SmallInteger(), nullable=False),
    sa.Column('sizes_hist', sa.JSON(), nullable=False),
    sa.Column('hamming_hist', sa.JSON(), nullable=False),
    sa.Column('perf_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('step_idx >= 0 AND step_idx <= 7', name='cc_dedup_step_idx_range'),
    sa.ForeignKeyConstraint(['run_id'], ['pipelinerun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'step_idx'),
    sa.UniqueConstraint('run_id', 'step_idx', name='uq_dedupdiagnostic_run_step_idx')
    )
    op.create_index('ix_dedup_run_id', 'dedupdiagnostic', ['run_id'], unique=False)
    op.create_table('extractiontemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('fields_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('outcomedefinition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('outcome_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('measure_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomedefinition_project_id'), 'outcomedefinition', ['project_id'], unique=False)
    op.create_table('pipelinestepresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.CHAR(length=32), nullable=False),
    sa.Column('step_index', sa.SmallInteger(), nullable=False),
    sa.Column('step_name', sa.String(length=32), nullable=False),
    sa.Column('attempt_no', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('n_inputs', sa.Integer(), nullable=False),
    sa.Column('n_outputs', sa.Integer(), nullable=False),
    sa.Column('payload_ref', sa.String(length=128), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipelinerun.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_index', 'attempt_no', name='uq_pipelinestep_run_step_attempt')
    )
    op.create_index('ix_pipelinestepresult_run_id', 'pipelinestepresult', ['run_id'], unique=False)
    op.create_table('prisma2020checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('item_1', sa.Boolean(), nullable=False),
    sa.Column('item_2', sa.Boolean(), nullable=False),
    sa.Column('item_3', sa.Boolean(), nullable=False),
    sa.Column('item_4', sa.Boolean(), nullable=False),
    sa.Column('item_5', sa.Boolean(), nullable=False),
    sa.Column('item_6', sa.Boolean(), nullable=False),
    sa.Column('item_7', sa.Boolean(), nullable=False),
    sa.Column('item_8', sa.Boolean(), nullable=False),
    sa.Column('item_9', sa.Boolean(), nullable=False),
    sa.Column('item_10', sa.Boolean(), nullable=False),
    sa.Column('item_11', sa.Boolean(), nullable=False),
    sa.Column('item_12', sa.Boolean(), nullable=False),
    sa.Column('item_13', sa.Boolean(), nullable=False),
    sa.Column('item_14', sa.Boolean(), nullable=False),
    sa.Column('item_15', sa.Boolean(), nullable=False),
    sa.Column('item_16', sa.Boolean(), nullable=False),
    sa.Column('item_17', sa.Boolean(), nullable=False),
    sa.Column('item_18', sa.Boolean(), nullable=False),
    sa.Column('item_19', sa.Boolean(), nullable=False),
    sa.Column('item_20', sa.Boolean(), nullable=False),
    sa.Column('item_21', sa.Boolean(), nullable=False),
    sa.Column('item_22', sa.Boolean(), nullable=False),
    sa.Column('item_23', sa.Boolean(), nullable=False),
    sa.Column('item_24', sa.Boolean(), nullable=False),
    sa.Column('item_25', sa.Boolean(), nullable=False),
    sa.Column('item_26', sa.Boolean(), nullable=False),
    sa.Column('item_27', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'reviewer_id', name='uq_prisma_project_reviewer')
    )
    op.create_index(op.f('ix_prisma2020checklist_project_id'), 'prisma2020checklist', ['project_id'], unique=False)
    op.create_index(op.f('ix_prisma2020checklist_reviewer_id'), 'prisma2020checklist', ['reviewer_id'], unique=False)
    op.create_table('reportsnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sha256_grade', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sha256_analysis', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('version_label', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('md_content', sa.Text(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('txt_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportsnapshot_project_id'), 'reportsnapshot', ['project_id'], unique=False)
    op.create_table('researchtaskrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchquery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latest_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchsourceconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('enabled_sources_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_fields_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('languages_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('analysisrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomedefinition.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysisrun_project_id'), 'analysisrun', ['project_id'], unique=False)
    op.create_table('gradeassessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('domains_5', sa.JSON(), nullable=False),
    sa.Column('upgrades_3', sa.JSON(), nullable=False),
    sa.Column('certainty_final', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomedefinition.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outcome_id', 'reviewer_id', name='uq_grade_outcome_reviewer')
    )
    op.create_index(op.f('ix_gradeassessment_outcome_id'), 'gradeassessment', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_gradeassessment_project_id'), 'gradeassessment', ['project_id'], unique=False)
    op.create_index(op.f('ix_gradeassessment_reviewer_id'), 'gradeassessment', ['reviewer_id'], unique=False)
    op.create_table('searchquerydraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('based_on_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grouped_terms_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expression_blocks_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_sources_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_dirty', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['searchquery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchqueryversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grouped_terms_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expression_blocks_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_sources_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['searchquery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('search_query_version_id', sa.Integer(), nullable=True),
    sa.Column('query_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_sources', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_hits_raw', sa.Integer(), nullable=False),
    sa.Column('total_after_dedupe', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.ForeignKeyConstraint(['search_query_version_id'], ['searchqueryversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searchrun_project_id'), 'searchrun', ['project_id'], unique=False)
    op.create_index(op.f('ix_searchrun_search_query_version_id'), 'searchrun', ['search_query_version_id'], unique=False)
    op.create_table('softablenode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('so_cols', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['gradeassessment.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomedefinition.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'outcome_id', name='uq_sof_project_outcome')
    )
    op.create_index(op.f('ix_softablenode_outcome_id'), 'softablenode', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_softablenode_project_id'), 'softablenode', ['project_id'], unique=False)
    op.create_table('searchrunsource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hits_on_source', sa.Integer(), nullable=True),
    sa.Column('records_retrieved', sa.Integer(), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_response_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['search_run_id'], ['searchrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searchrunsource_search_run_id'), 'searchrunsource', ['search_run_id'], unique=False)
    op.create_index(op.f('ix_searchrunsource_source_key'), 'searchrunsource', ['source_key'], unique=False)
    op.create_table('literatureimportbatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_at_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_run_source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.ForeignKeyConstraint(['search_run_source_id'], ['searchrunsource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('literaturerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authors', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('journal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pmid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dedupe_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('search_run_id', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('pico_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('screening_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('screening_decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exclude_reason_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('screening_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['literaturerecord.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['literatureimportbatch.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.ForeignKeyConstraint(['search_run_id'], ['searchrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidenceartifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('literature_record_id', sa.Integer(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('exclude_reason_ids', sa.JSON(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('override_by_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['literature_record_id'], ['literaturerecord.id'], ),
    sa.ForeignKeyConstraint(['override_by_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('literature_record_id', 'stage', name='uq_evidenceartifact_lr_stage')
    )
    op.create_index(op.f('ix_evidenceartifact_literature_record_id'), 'evidenceartifact', ['literature_record_id'], unique=False)
    op.create_table('extractioncell',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['literaturerecord.id'], ),
    sa.PrimaryKeyConstraint('record_id', 'field_key', 'reviewer_id')
    )
    op.create_index(op.f('ix_extractioncell_project_id'), 'extractioncell', ['project_id'], unique=False)
    op.create_table('literaturepico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('population', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intervention', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comparison', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('study_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extraction_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['literaturerecord.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_table('outcomearmdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('arm_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomedefinition.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['researchproject.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['literaturerecord.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomearmdata_outcome_id'), 'outcomearmdata', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_outcomearmdata_project_id'), 'outcomearmdata', ['project_id'], unique=False)
    op.create_index(op.f('ix_outcomearmdata_record_id'), 'outcomearmdata', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcomearmdata_record_id'), table_name='outcomearmdata')
    op.drop_index(op.f('ix_outcomearmdata_project_id'), table_name='outcomearmdata')
    op.drop_index(op.f('ix_outcomearmdata_outcome_id'), table_name='outcomearmdata')
    op.drop_table('outcomearmdata')
    op.drop_table('literaturepico')
    op.drop_index(op.f('ix_extractioncell_project_id'), table_name='extractioncell')
    op.drop_table('extractioncell')
    op.drop_index(op.f('ix_evidenceartifact_literature_record_id'), table_name='evidenceartifact')
    op.drop_table('evidenceartifact')
    op.drop_table('literaturerecord')
    op.drop_table('literatureimportbatch')
    op.drop_index(op.f('ix_searchrunsource_source_key'), table_name='searchrunsource')
    op.drop_index(op.f('ix_searchrunsource_search_run_id'), table_name='searchrunsource')
    op.drop_table('searchrunsource')
    op.drop_index(op.f('ix_softablenode_project_id'), table_name='softablenode')
    op.drop_index(op.f('ix_softablenode_outcome_id'), table_name='softablenode')
    op.drop_table('softablenode')
    op.drop_index(op.f('ix_searchrun_search_query_version_id'), table_name='searchrun')
    op.drop_index(op.f('ix_searchrun_project_id'), table_name='searchrun')
    op.drop_table('searchrun')
    op.drop_table('searchqueryversion')
    op.drop_table('searchquerydraft')
    op.drop_index(op.f('ix_gradeassessment_reviewer_id'), table_name='gradeassessment')
    op.drop_index(op.f('ix_gradeassessment_project_id'), table_name='gradeassessment')
    op.drop_index(op.f('ix_gradeassessment_outcome_id'), table_name='gradeassessment')
    op.drop_table('gradeassessment')
    op.drop_index(op.f('ix_analysisrun_project_id'), table_name='analysisrun')
    op.drop_table('analysisrun')
    op.drop_table('searchsourceconfig')
    op.drop_table('searchquery')
    op.drop_table('researchtaskrecord')
    op.drop_index(op.f('ix_reportsnapshot_project_id'), table_name='reportsnapshot')
    op.drop_table('reportsnapshot')
    op.drop_index(op.f('ix_prisma2020checklist_reviewer_id'), table_name='prisma2020checklist')
    op.drop_index(op.f('ix_prisma2020checklist_project_id'), table_name='prisma2020checklist')
    op.drop_table('prisma2020checklist')
    op.drop_index('ix_pipelinestepresult_run_id', table_name='pipelinestepresult')
    op.drop_table('pipelinestepresult')
    op.drop_index(op.f('ix_outcomedefinition_project_id'), table_name='outcomedefinition')
    op.drop_table('outcomedefinition')
    op.drop_table('extractiontemplate')
    op.drop_index('ix_dedup_run_id', table_name='dedupdiagnostic')
    op.drop_table('dedupdiagnostic')
    op.drop_table('researchproject')
    op.drop_index(op.f('ix_pipelinerun_workspace_id'), table_name='pipelinerun')
    op.drop_index(op.f('ix_pipelinerun_status'), table_name='pipelinerun')
    op.drop_index(op.f('ix_pipelinerun_preset'), table_name='pipelinerun')
    op.drop_table('pipelinerun')
    op.drop_table('membership')
    op.drop_table('authsession')
    op.drop_table('workspace')
    op.drop_table('user')
    op.drop_table('organization')
    op.drop_table('filerecord')
    op.drop_table('auditevent')
    op.drop_table('artifactrecord')
    # ### end Alembic commands ###
