<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-03-11 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content",
            field=models.TextField(
                blank=True, help_text="Content for online documents", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_online",
            field=models.BooleanField(
                default=False, help_text="True if document is created/edited online"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="content",
            field=models.TextField(
                blank=True, help_text="Content for online documents", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="is_online",
            field=models.BooleanField(
                default=False, help_text="True if document is created/edited online"
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
=======
=======
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
=======
>>>>>>> origin/main
# Generated by Django 5.1.15 on 2026-03-11 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content",
            field=models.TextField(
                blank=True, help_text="Content for online documents", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_online",
            field=models.BooleanField(
                default=False, help_text="True if document is created/edited online"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="content",
            field=models.TextField(
                blank=True, help_text="Content for online documents", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="is_online",
            field=models.BooleanField(
                default=False, help_text="True if document is created/edited online"
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
=======
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
=======
>>>>>>> origin/main
