<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-03-10 06:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSubject",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("subject_initials", models.CharField(max_length=5)),
                ("subject_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCREENING", "Screening"),
                            ("SCREEN_FAIL", "Screen Failure"),
                            ("ENROLLED", "Enrolled"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SCREENING",
                        max_length=20,
                    ),
                ),
                (
                    "informed_consent_date",
                    models.DateField(help_text="Date ICF signed"),
                ),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                ("withdrawal_date", models.DateField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trials.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical subject",
                "verbose_name_plural": "historical subjects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_initials", models.CharField(max_length=5)),
                ("subject_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCREENING", "Screening"),
                            ("SCREEN_FAIL", "Screen Failure"),
                            ("ENROLLED", "Enrolled"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SCREENING",
                        max_length=20,
                    ),
                ),
                (
                    "informed_consent_date",
                    models.DateField(help_text="Date ICF signed"),
                ),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                ("withdrawal_date", models.DateField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="trials.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "subject_number")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalVisit",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("visit_name", models.CharField(max_length=50)),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Visit sequence order"),
                ),
                (
                    "target_date",
                    models.DateField(
                        help_text="Projected visit date based on protocol"
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        blank=True, help_text="Actual visit date", null=True
                    ),
                ),
                (
                    "window_days",
                    models.PositiveIntegerField(
                        default=7, help_text="+/- days allowed"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("EMPTY", "Empty"),
                            ("PARTIAL", "Partial"),
                            ("COMPLETE", "Complete"),
                            ("VERIFIED", "Verified (SDV Done)"),
                            ("LOCKED", "Locked"),
                        ],
                        default="EMPTY",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical visit",
                "verbose_name_plural": "historical visits",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_name", models.CharField(max_length=50)),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Visit sequence order"),
                ),
                (
                    "target_date",
                    models.DateField(
                        help_text="Projected visit date based on protocol"
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        blank=True, help_text="Actual visit date", null=True
                    ),
                ),
                (
                    "window_days",
                    models.PositiveIntegerField(
                        default=7, help_text="+/- days allowed"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("EMPTY", "Empty"),
                            ("PARTIAL", "Partial"),
                            ("COMPLETE", "Complete"),
                            ("VERIFIED", "Verified (SDV Done)"),
                            ("LOCKED", "Locked"),
                        ],
                        default="EMPTY",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "order"],
                "unique_together": {("subject", "visit_name")},
            },
        ),
    ]
=======
# Generated by Django 5.1.15 on 2026-03-10 06:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSubject",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("subject_initials", models.CharField(max_length=5)),
                ("subject_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCREENING", "Screening"),
                            ("SCREEN_FAIL", "Screen Failure"),
                            ("ENROLLED", "Enrolled"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SCREENING",
                        max_length=20,
                    ),
                ),
                (
                    "informed_consent_date",
                    models.DateField(help_text="Date ICF signed"),
                ),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                ("withdrawal_date", models.DateField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trials.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical subject",
                "verbose_name_plural": "historical subjects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_initials", models.CharField(max_length=5)),
                ("subject_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCREENING", "Screening"),
                            ("SCREEN_FAIL", "Screen Failure"),
                            ("ENROLLED", "Enrolled"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SCREENING",
                        max_length=20,
                    ),
                ),
                (
                    "informed_consent_date",
                    models.DateField(help_text="Date ICF signed"),
                ),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                ("withdrawal_date", models.DateField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="trials.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "subject_number")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalVisit",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("visit_name", models.CharField(max_length=50)),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Visit sequence order"),
                ),
                (
                    "target_date",
                    models.DateField(
                        help_text="Projected visit date based on protocol"
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        blank=True, help_text="Actual visit date", null=True
                    ),
                ),
                (
                    "window_days",
                    models.PositiveIntegerField(
                        default=7, help_text="+/- days allowed"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("EMPTY", "Empty"),
                            ("PARTIAL", "Partial"),
                            ("COMPLETE", "Complete"),
                            ("VERIFIED", "Verified (SDV Done)"),
                            ("LOCKED", "Locked"),
                        ],
                        default="EMPTY",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical visit",
                "verbose_name_plural": "historical visits",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_name", models.CharField(max_length=50)),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Visit sequence order"),
                ),
                (
                    "target_date",
                    models.DateField(
                        help_text="Projected visit date based on protocol"
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        blank=True, help_text="Actual visit date", null=True
                    ),
                ),
                (
                    "window_days",
                    models.PositiveIntegerField(
                        default=7, help_text="+/- days allowed"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("EMPTY", "Empty"),
                            ("PARTIAL", "Partial"),
                            ("COMPLETE", "Complete"),
                            ("VERIFIED", "Verified (SDV Done)"),
                            ("LOCKED", "Locked"),
                        ],
                        default="EMPTY",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "order"],
                "unique_together": {("subject", "visit_name")},
            },
        ),
    ]
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
