<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-03-10 07:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSpecimen",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("specimen_id", models.CharField(db_index=True, max_length=50)),
                (
                    "specimen_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood"),
                            ("URINE", "Urine"),
                            ("TISSUE", "Tissue"),
                            ("SERUM", "Serum"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("collection_date", models.DateTimeField()),
                ("storage_location", models.CharField(max_length=255)),
                ("status", models.CharField(default="COLLECTED", max_length=20)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical specimen",
                "verbose_name_plural": "historical specimens",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specimen_id", models.CharField(max_length=50, unique=True)),
                (
                    "specimen_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood"),
                            ("URINE", "Urine"),
                            ("TISSUE", "Tissue"),
                            ("SERUM", "Serum"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("collection_date", models.DateTimeField()),
                ("storage_location", models.CharField(max_length=255)),
                ("status", models.CharField(default="COLLECTED", max_length=20)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimens",
                        to="subjects.subject",
                    ),
                ),
            ],
        ),
    ]
=======
=======
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
=======
>>>>>>> origin/main
# Generated by Django 5.1.15 on 2026-03-10 07:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSpecimen",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("specimen_id", models.CharField(db_index=True, max_length=50)),
                (
                    "specimen_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood"),
                            ("URINE", "Urine"),
                            ("TISSUE", "Tissue"),
                            ("SERUM", "Serum"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("collection_date", models.DateTimeField()),
                ("storage_location", models.CharField(max_length=255)),
                ("status", models.CharField(default="COLLECTED", max_length=20)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical specimen",
                "verbose_name_plural": "historical specimens",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specimen_id", models.CharField(max_length=50, unique=True)),
                (
                    "specimen_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood"),
                            ("URINE", "Urine"),
                            ("TISSUE", "Tissue"),
                            ("SERUM", "Serum"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("collection_date", models.DateTimeField()),
                ("storage_location", models.CharField(max_length=255)),
                ("status", models.CharField(default="COLLECTED", max_length=20)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimens",
                        to="subjects.subject",
                    ),
                ),
            ],
        ),
    ]
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
=======
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
=======
>>>>>>> origin/main
