# Generated by Django 5.1.15 on 2026-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_historicalspecimen_specimen"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvisit",
            name="is_monitored",
            field=models.BooleanField(default=False, help_text="SDV Completed"),
        ),
        migrations.AddField(
            model_name="visit",
            name="is_monitored",
            field=models.BooleanField(default=False, help_text="SDV Completed"),
        ),
        migrations.AlterField(
            model_name="historicalvisit",
            name="data_status",
            field=models.CharField(
                choices=[
                    ("EMPTY", "Empty"),
                    ("PARTIAL", "Partial"),
                    ("COMPLETE", "Complete"),
                    ("VERIFIED", "Verified (SDV Done)"),
                    ("SIGNED", "Signed (e-Signature)"),
                    ("LOCKED", "Locked"),
                ],
                default="EMPTY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="data_status",
            field=models.CharField(
                choices=[
                    ("EMPTY", "Empty"),
                    ("PARTIAL", "Partial"),
                    ("COMPLETE", "Complete"),
                    ("VERIFIED", "Verified (SDV Done)"),
                    ("SIGNED", "Signed (e-Signature)"),
                    ("LOCKED", "Locked"),
                ],
                default="EMPTY",
                max_length=20,
            ),
        ),
    ]
