<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-03-10 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0003_historicalvisit_is_monitored_visit_is_monitored_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvisit",
            name="data",
            field=models.JSONField(blank=True, default=dict, help_text="CRF Data"),
        ),
        migrations.AddField(
            model_name="historicalvisit",
            name="monitored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalvisit",
            name="monitored_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="data",
            field=models.JSONField(blank=True, default=dict, help_text="CRF Data"),
        ),
        migrations.AddField(
            model_name="visit",
            name="monitored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="monitored_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitored_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
=======
# Generated by Django 5.1.15 on 2026-03-10 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0003_historicalvisit_is_monitored_visit_is_monitored_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvisit",
            name="data",
            field=models.JSONField(blank=True, default=dict, help_text="CRF Data"),
        ),
        migrations.AddField(
            model_name="historicalvisit",
            name="monitored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalvisit",
            name="monitored_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="data",
            field=models.JSONField(blank=True, default=dict, help_text="CRF Data"),
        ),
        migrations.AddField(
            model_name="visit",
            name="monitored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="monitored_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitored_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
