# Generated by Django 5.1.15 on 2026-03-10 06:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdverseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_term",
                    models.CharField(help_text="AE description", max_length=255),
                ),
                ("onset_date", models.DateTimeField()),
                ("resolution_date", models.DateTimeField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MILD", "Mild"),
                            ("MODERATE", "Moderate"),
                            ("SEVERE", "Severe"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_serious",
                    models.CharField(
                        choices=[("YES", "Yes (SAE)"), ("NO", "No (AE)")],
                        default="NO",
                        max_length=5,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("NOT_RELATED", "Not Related"),
                            ("UNLIKELY", "Unlikely Related"),
                            ("POSSIBLY", "Possibly Related"),
                            ("PROBABLY", "Probably Related"),
                            ("DEFINITELY", "Definitely Related"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("RECOVERED", "Recovered/Resolved"),
                            ("RECOVERING", "Recovering/Resolving"),
                            ("NOT_RECOVERED", "Not Recovered/Not Resolved"),
                            (
                                "RECOVERED_WITH_SEQUELAE",
                                "Recovered/Resolved with Sequelae",
                            ),
                            ("FATAL", "Fatal"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "meddra_code",
                    models.CharField(
                        blank=True,
                        help_text="System Organ Class / Preferred Term",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_susar",
                    models.BooleanField(
                        default=False,
                        help_text="Suspected Unexpected Serious Adverse Reaction",
                    ),
                ),
                ("reported_to_pv_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reported_to_regulatory_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_aes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adverse_events",
                        to="subjects.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalAdverseEvent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "event_term",
                    models.CharField(help_text="AE description", max_length=255),
                ),
                ("onset_date", models.DateTimeField()),
                ("resolution_date", models.DateTimeField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MILD", "Mild"),
                            ("MODERATE", "Moderate"),
                            ("SEVERE", "Severe"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_serious",
                    models.CharField(
                        choices=[("YES", "Yes (SAE)"), ("NO", "No (AE)")],
                        default="NO",
                        max_length=5,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("NOT_RELATED", "Not Related"),
                            ("UNLIKELY", "Unlikely Related"),
                            ("POSSIBLY", "Possibly Related"),
                            ("PROBABLY", "Probably Related"),
                            ("DEFINITELY", "Definitely Related"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("RECOVERED", "Recovered/Resolved"),
                            ("RECOVERING", "Recovering/Resolving"),
                            ("NOT_RECOVERED", "Not Recovered/Not Resolved"),
                            (
                                "RECOVERED_WITH_SEQUELAE",
                                "Recovered/Resolved with Sequelae",
                            ),
                            ("FATAL", "Fatal"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "meddra_code",
                    models.CharField(
                        blank=True,
                        help_text="System Organ Class / Preferred Term",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_susar",
                    models.BooleanField(
                        default=False,
                        help_text="Suspected Unexpected Serious Adverse Reaction",
                    ),
                ),
                ("reported_to_pv_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reported_to_regulatory_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical adverse event",
                "verbose_name_plural": "historical adverse events",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
