import os
import glob

def generate_index_html():
    output_dir = r"d:\workspace\Digital_Twin_Project\output"
    html_files = glob.glob(os.path.join(output_dir, "*.html"))
    
    # 按患者分组文件
    patients = {}
    for f in html_files:
        filename = os.path.basename(f)
        if filename == "index.html":
            continue
            
        # 提取姓名 (第一个下划线前的所有内容)
        # 假设格式为 "姓名_后缀.html"
        parts = filename.split('_')
        name = parts[0]
        
        if name not in patients:
            patients[name] = {'baseline': None, 'evolution': None, 'intensive': None}
            
        if 'intensive_evolution_viz' in filename:
            patients[name]['intensive'] = filename
        elif 'evolution_viz' in filename:
            patients[name]['evolution'] = filename
        elif 'spine_model' in filename and 'Predicted' not in filename:
            patients[name]['baseline'] = filename

    # 生成 HTML 内容
    html_content = """
    <!DOCTYPE html>
    <html lang="zh-CN">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>脊柱数字孪生 - 患者仪表盘</title>
        <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
            .container { max-width: 1000px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
            h1 { color: #2c3e50; text-align: center; margin-bottom: 30px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { padding: 15px; text-align: left; border-bottom: 1px solid #ddd; }
            th { background-color: #3498db; color: white; }
            tr:hover { background-color: #f1f1f1; }
            a { text-decoration: none; color: #3498db; font-weight: bold; }
            a:hover { text-decoration: underline; color: #2980b9; }
            .status-badge { padding: 5px 10px; border-radius: 15px; font-size: 0.85em; }
            .status-ready { background-color: #e8f8f5; color: #27ae60; border: 1px solid #27ae60; }
            .status-missing { background-color: #fdedec; color: #c0392b; border: 1px solid #c0392b; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>脊柱数字孪生 - 患者数据总览</h1>
            <table>
                <thead>
                    <tr>
                        <th>患者姓名</th>
                        <th>基线模型 (当前状态)</th>
                        <th>预测演变 (常规干预)</th>
                        <th>强化干预 (效果对比)</th>
                    </tr>
                </thead>
                <tbody>
    """
    
    for name in sorted(patients.keys()):
        baseline = patients[name]['baseline']
        evolution = patients[name]['evolution']
        intensive = patients[name].get('intensive')
        
        html_content += f"<tr><td>{name}</td>"
        
        if baseline:
            html_content += f'<td><a href="{baseline}" target="_blank">查看 3D 模型</a> <span class="status-badge status-ready">已生成</span></td>'
        else:
            html_content += '<td><span class="status-badge status-missing">未找到</span></td>'
            
        if evolution:
            html_content += f'<td><a href="{evolution}" target="_blank">查看预测模拟</a> <span class="status-badge status-ready">已生成</span></td>'
        else:
            html_content += '<td><span class="status-badge status-missing">未找到</span></td>'
            
        if intensive:
            html_content += f'<td><a href="{intensive}" target="_blank" style="color:#e67e22">查看强化效果</a> <span class="status-badge status-ready">已生成</span></td>'
        else:
            html_content += '<td><span class="status-badge status-missing">未找到</span></td>'
            
        html_content += "</tr>"

    html_content += """
                </tbody>
            </table>
            <p style="text-align: center; margin-top: 30px; color: #7f8c8d; font-size: 0.9em;">
                Generated by Digital Twin System
            </p>
        </div>
    </body>
    </html>
    """

    with open(os.path.join(output_dir, "index.html"), 'w', encoding='utf-8') as f:
        f.write(html_content)
        
    print(f"索引文件已生成: {os.path.join(output_dir, 'index.html')}")

if __name__ == "__main__":
    generate_index_html()
