# Generated by Django 5.1.15 on 2026-03-10 06:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTrial",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("protocol_number", models.CharField(db_index=True, max_length=50)),
                ("title", models.CharField(max_length=255)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("I", "Phase I"),
                            ("II", "Phase II"),
                            ("III", "Phase III"),
                            ("IV", "Phase IV"),
                            ("BE", "Bioequivalence"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sponsor", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted to IRB"),
                            ("APPROVED", "IRB Approved"),
                            ("ACTIVE", "Active (Enrolling)"),
                            ("LOCKED", "Database Locked"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"role": "PM"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical trial",
                "verbose_name_plural": "historical trials",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("I", "Phase I"),
                            ("II", "Phase II"),
                            ("III", "Phase III"),
                            ("IV", "Phase IV"),
                            ("BE", "Bioequivalence"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sponsor", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted to IRB"),
                            ("APPROVED", "IRB Approved"),
                            ("ACTIVE", "Active (Enrolling)"),
                            ("LOCKED", "Database Locked"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_manager",
                    models.ForeignKey(
                        limit_choices_to={"role": "PM"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_trials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalSite",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("site_number", models.CharField(max_length=20)),
                ("name", models.CharField(help_text="Hospital Name", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SELECTED", "Selected"),
                            ("INITIATED", "Initiated"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="SELECTED",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assigned_cra",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"role": "CRA"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "principal_investigator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"role": "INV"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trials.trial",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical site",
                "verbose_name_plural": "historical sites",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_number", models.CharField(max_length=20)),
                ("name", models.CharField(help_text="Hospital Name", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SELECTED", "Selected"),
                            ("INITIATED", "Initiated"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="SELECTED",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_cra",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "CRA"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitored_sites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "principal_investigator",
                    models.ForeignKey(
                        limit_choices_to={"role": "INV"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pi_sites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="trials.trial",
                    ),
                ),
            ],
            options={
                "unique_together": {("trial", "site_number")},
            },
        ),
    ]
