<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-03-10 07:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalInvestigationalProduct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("DRUG", "Drug"),
                            ("DEVICE", "Device"),
                            ("BIOLOGIC", "Biologic"),
                            ("SUPPLY", "Supply"),
                        ],
                        default="DRUG",
                        max_length=20,
                    ),
                ),
                ("batch_number", models.CharField(max_length=50)),
                ("expiry_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trials.trial",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical investigational product",
                "verbose_name_plural": "historical investigational products",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="InvestigationalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("DRUG", "Drug"),
                            ("DEVICE", "Device"),
                            ("BIOLOGIC", "Biologic"),
                            ("SUPPLY", "Supply"),
                        ],
                        default="DRUG",
                        max_length=20,
                    ),
                ),
                ("batch_number", models.CharField(max_length=50)),
                ("expiry_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="trials.trial",
                    ),
                ),
            ],
        ),
    ]
=======
=======
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
# Generated by Django 5.1.15 on 2026-03-10 07:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalInvestigationalProduct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("DRUG", "Drug"),
                            ("DEVICE", "Device"),
                            ("BIOLOGIC", "Biologic"),
                            ("SUPPLY", "Supply"),
                        ],
                        default="DRUG",
                        max_length=20,
                    ),
                ),
                ("batch_number", models.CharField(max_length=50)),
                ("expiry_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trials.trial",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical investigational product",
                "verbose_name_plural": "historical investigational products",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="InvestigationalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("DRUG", "Drug"),
                            ("DEVICE", "Device"),
                            ("BIOLOGIC", "Biologic"),
                            ("SUPPLY", "Supply"),
                        ],
                        default="DRUG",
                        max_length=20,
                    ),
                ),
                ("batch_number", models.CharField(max_length=50)),
                ("expiry_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="trials.trial",
                    ),
                ),
            ],
        ),
    ]
<<<<<<< HEAD
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
=======
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
