<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-03-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0002_historicalinvestigationalproduct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltrial",
            name="archive_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrial",
            name="db_lock_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrial",
            name="irb_approval_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrial",
            name="irb_approval_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trial",
            name="archive_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="db_lock_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="irb_approval_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="irb_approval_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
=======
=======
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
# Generated by Django 5.1.15 on 2026-03-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0002_historicalinvestigationalproduct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltrial",
            name="archive_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrial",
            name="db_lock_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrial",
            name="irb_approval_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrial",
            name="irb_approval_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trial",
            name="archive_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="db_lock_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="irb_approval_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="irb_approval_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
<<<<<<< HEAD
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
=======
>>>>>>> 9750b2979c0547a41eee960f69d088078d2151a8
