# Generated by Django 5.1.15 on 2026-03-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0003_historicaltrial_archive_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="trial",
            options={"ordering": ["-created_at"]},
        ),
    ]
