#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
扩展医学翻译器 - 专门针对未翻译的 CDISC 术语
重点覆盖：微生物、解剖位置、PK 单位、方法、剂型等
"""

class ExtendedMedicalTranslator:
    def __init__(self):
        # ========== 微生物学 (Microorganism) ==========
        self.microorganism_terms = {
            # 细菌
            'ACINETOBACTER BAUMANNII': '伯克霍尔德菌属 曼海姆氏不动杆菌',
            'ACINETOBACTER CALCOACETUS': '不动杆菌属 嗜钙不动杆菌',
            'ACINETOBACTER IOWENSIS': '不动杆菌属 爱荷华不动杆菌',
            'ACINETOBACTER LWOFFII': '不动杆菌属 娄氏不动杆菌',
            'ACINETOBACTER': '不动杆菌属',
            'ACTINOBACILLUS ACTINOMYCETEMCOMITANS': '放线杆菌属 伴放线放线杆菌',
            'ACTINOBACILLUS': '放线杆菌属',
            'ACTINOMYCES': '放线菌属',
            'AEROMONAS': '气单胞菌属',
            'AEROMONAS HYDROPHILA': '气单胞菌属 亲水气单胞菌',
            'AGGREGATIBACTER ACTINOMYCEMCOMITANS': '凝聚胺杆菌属 伴放线凝聚胺杆菌',
            'ALCALIGENES': '碱杆菌属',
            'ALTERMONAS': '变形菌属',
            'ANAEROBACTER': '厌氧杆菌属',
            'ANAPLASMOSIS': '埃立克体病',
            'ANAPLASMA': '埃立克体属',
            'ANTHROPOPHAGUS': '食人菌',
            'ARCANOBACTERIUM HAEMOLYTICUM': '隐秘杆菌属 溶血隐秘杆菌',
            'ARTHROBAACTER': '小单胞菌属',
            'ASTERICOLA': '星形菌属',
            'ATOPOBIMUM': '阿托普菌属',
            'AVIBACTAM': '阿维巴坦',
            'AVIBACTAM-RESISTANT': '阿维巴坦耐药',
            'AZITHROMYCIN': '阿奇霉素',
            'BACILLUS': '芽孢杆菌属',
            'BACTEROIDES': '拟杆菌属',
            'BALNEIGLLA': '温泉菌属',
            'BARTONELLA': '巴尔通体属',
            'BIFIDOBACTERIUM': '双歧杆菌属',
            'BORDETELLA': '博德特菌属',
            'BORRELIA': '伯氏疏螺旋体属',
            'BREVIBACTERIUM': '短杆菌属',
            'CAENOCOCCUS': '腔球菌属',
            'CAMPYLOBACTER': '弯曲杆菌属',
            'CAPNOCYTOPHAGA': '产气噬纤维菌属',
            'CARDIOBACTERIUM': '心脏菌属',
            'CHLAMYDIA': '衣原体属',
            'CHLAMYDOPHLA': '嗜衣原体属',
            'CHROMOBACTERIUM': '色杆菌属',
            'CHRYSEOBACTERIUM': '金黄色杆菌属',
            'CITROBACTER': '肠杆菌属',
            'COAGULASE-NEGATIVE STAPHYLOCOCCUS': '凝固酶阴性葡萄球菌',
            'CORYNEBACTERIUM': '棒状杆菌属',
            'CRASSOSTREA GIGAS': '太平洋牡蛎',
            'CRYSTALLOBACTER': '晶形菌属',
            'CURTObACTERIUM': '柯曲氏菌属',
            'CUTIBACTERIUM ACNES': '皮肤杆菌属 痤疮皮肤杆菌',
            'DERMATOBACTER': '皮肤菌属',
            'DICKEYA': '狄克氏菌属',
            'DIETERIA': '狄特里希菌属',
            'EGGERTHELLA': '埃格特菌属',
            'EGGERTHELLA LENTA': '埃格特菌属 缓慢埃格特菌',
            'EICHHORNIA CRASSIPES': '水葫芦',
            'EIKENELLA CORRODENS': '艾肯菌属 具核艾肯菌',
            'ELKSTONIA': '埃尔克斯顿菌属',
            'ENTEROBACTER': '肠杆菌属',
            'ENTEROCOCCUS': '肠球菌属',
            'ENTEROCOCCUS CASSIEFLAVUS': '肠球菌属 卡西黄肠球菌',
            'ENTEROCOCCUS FECALIS': '肠球菌属 粪肠球菌',
            'ENTEROCOCCUS FECIUM': '肠球菌属 屎肠球菌',
            'ENTEROCOCCUS HALLI': '肠球菌属 霍尔肠球菌',
            'ENTEROCOCCUS RAFINOSUS': '肠球菌属 拉菲诺肠球菌',
            'ENTEROCOCCUS': '肠球菌属',
            'ERWIA': '欧氏菌属',
            'ESCHERICHIA COLI': '大肠埃希菌',
            'ESCHERICHIA': '埃希菌属',
            'EUSSERELLA': '欧塞尔菌属',
            'EXIGUOBACTERIUM': '寡养单胞菌属',
            'FAECALIBACTERIUM': '粪杆菌属',
            'FAECALIBACTERIUM PRAUSNITZII': '粪杆菌属 普氏粪杆菌',
            'FUSOBACTERIUM': '梭杆菌属',
            'GARDNERELLA VAGINALIS': '加德纳菌属 阴道加德纳菌',
            'GEOBACILLUS': '地芽孢杆菌属',
            'GEOTRICHUM': '地霉属',
            'HAEMOPHILUS': '嗜血杆菌属',
            'HAEMOPHILUS INFLUENZAE': '嗜血杆菌属 流感嗜血杆菌',
            'HELIcobACTER PYLORI': '幽门螺杆菌',
            'HERPES SIMPLEX VIRUS 1': '单纯疱疹病毒 1 型',
            'HERPES SIMPLEX VIRUS 2': '单纯疱疹病毒 2 型',
            'HINSHAWELLA': '欣肖菌属',
            'HOEFLEA': '霍夫勒菌属',
            'HOMINAHABAX': '人栖菌属',
            'HYALINOBACTER': '透明杆菌属',
            'IGNIAVIBRIO': '火弧菌属',
            'LEGIONELLA': '军团菌属',
            'LEPTOTRICHIA': '细丝菌属',
            'LEVANS': '菊粉',
            'LOEPHOTHRIX': '毛样菌属',
            'LISTERIA': '李斯特菌属',
            'LISTERIA MONOCYTOGENES': '李斯特菌属 单核细胞增生李斯特菌',
            'MOBILUNUS': '移动菌属',
            'MYCOBACTERIUM': '分枝杆菌属',
            'MYCOPLASMA': '支原体属',
            'NEISSERIA': '奈瑟菌属',
            'NEISSERIA GONORRHOEAE': '奈瑟菌属 淋病奈瑟菌',
            'NEISSERIA MENINGITIDIS': '奈瑟菌属 脑膜炎奈瑟菌',
            'NOCARDIA': '诺卡菌属',
            'NOSTOC': '念珠藻属',
            'NUCHITELLA': '颈丛菌属',
            'OCALIGENES': '产碱菌属',
            'ODORIBACTER': '产臭菌属',
            'OHGAS': '吴氏菌属',
            'ORNITHINICOLA': '鸟氨酸菌属',
            'PASTEURELLA': '巴斯德菌属',
            'PEDOBACTER': '土杆菌属',
            'PEPTOCOCCUS': '肽球菌属',
            'PEPTOSTREPTOCOCCUS': '肽链球菌属',
            'PHASINICONCOLA': '相形菌属',
            'PHOTORHODOBACTER': '光红杆菌属',
            'PHREATOBACTER': '泉杆菌属',
            'PLANKTOTHRIX': '浮丝藻属',
            'PLESIOMONAS': '邻单胞菌属',
            'PNEUMOCYSTIS JIROVECI': '耶氏肺孢子菌',
            'POLYMICEXIBACTIN': '多黏菌素',
            'PORPHYROMONAS': '普雷沃菌属',
            'PROVIBRIO': '原弧菌属',
            'PROTEUS': '变形杆菌属',
            'PROVIBRIO': '原弧菌属',
            'PSYCHROFLEXUS': '冷屈杆菌属',
            'PSYCHROMONAS': '冷单胞菌属',
            'PSEUDOMONAS': '假单胞菌属',
            'PSEUDOMONAS AERUGINOSA': '假单胞菌属 铜绿假单胞菌',
            'PSEUDOMONAS PUTIDA': '假单胞菌属 恶臭假单胞菌',
            'PSEUDOMONAS STUTZERII': '假单胞菌属 斯氏假单胞菌',
            'PYRROMONAS': '吡咯单胞菌属',
            'RAMICATA': '分枝菌属',
            'RHODOCOCUS': '红球菌属',
            'RHODOPSEUDOMONAS': '红假单胞菌属',
            'RHODOSPILLUM': '红螺菌属',
            'RHODOTORULA': '红酵母属',
            'RHODOVIBRIO': '红弧菌属',
            'RISSOELLA': '里索菌属',
            'ROBLINELLA': '罗布林菌属',
            'SACCHAROMYCES': '酵母属',
            'SALEMENACACEAE': '萨莱门纳科',
            'SALMONELLA': '沙门菌属',
            'SALMONELLA TYPHIMURIUM': '沙门菌属 鼠伤寒沙门菌',
            'SCOPULICIBARIUM': '岩菌属',
            'SERRATIA': '沙雷菌属',
            'SHIGELLA': '志贺菌属',
            'SHINELLAA': '希内拉菌属',
            'SHINELLA': '希内拉菌属',
            'SPHINGOBACTERIUM': '鞘氨醇杆菌属',
            'SPHINGOMONAS': '鞘氨醇单胞菌属',
            'SPROTOCELLA': '原球菌属',
            'STAPHYLOCOCCUS': '葡萄球菌属',
            'STAPHYLOCOCCUS AUREUS': '葡萄球菌属 金黄色葡萄球菌',
            'STREPTOCOCCUS': '链球菌属',
            'STREPTOCOCCUS PNEUMONIAE': '链球菌属 肺炎链球菌',
            'STREPTOCOCCUS PYOGENES': '链球菌属 化脓链球菌',
            'STREPTOMYCES': '链霉菌属',
            'TERRIBACTER': '地杆菌属',
            'TREPONEMA': '密螺旋体属',
            'TRICHODERMA': '木霉菌属',
            'TRIPLOSTICHUS': '三刺鱼属',
            'TURICIBACTER': '土利西菌属',
            'TURICIBACTER CUTIS': '土利西菌属 皮肤土利西菌',
            'TYPHLOMYCES': '盲肠菌属',
            'UBA': '乌巴菌属',
            'UREAPLASMA': '脲原体属',
            'VAGOCoccus': '阴道球菌属',
            'VAGOCoccus FLAVUS': '阴道球菌属 黄色阴道球菌',
            'VIBRIO': '弧菌属',
            'VIBRIO CHOLERAE': '弧菌属 霍乱弧菌',
            'WEBSTERELLA': '韦伯斯特菌属',
            'WEISSELAEA': '魏丝菌属',
            'WOLINELLA': '沃林菌属',
            'YERSINIA': '耶尔森菌属',
            'YERSINIA ENTEROCOLITICA': '耶尔森菌属 小肠结肠炎耶尔森菌',
            
            # 真菌
            'CANDIDA': '假丝酵母属',
            'CANDIDA ALBICANS': '假丝酵母属 白假丝酵母',
            'CANDIDA GLABRATA': '假丝酵母属 光滑假丝酵母',
            'CANDIDA KRUSEI': '假丝酵母属 克鲁斯假丝酵母',
            'CANDIDA TROPICALIS': '假丝酵母属 热带假丝酵母',
            'ASPERGILLUS': '曲霉属',
            'ASPERGILLUS FUMIGATUS': '曲霉属 烟曲霉',
            'CRYPTOCOCCUS': '隐球菌属',
            'CRYPTOCOCCUS NEOFORMANS': '隐球菌属 新型隐球菌',
            'TRICHOPHYTON': '毛癣菌属',
            'MICROSPORUM': '小孢子菌属',
            'EPIDERMOPHyton': '表皮癣菌属',
            
            # 病毒
            'ADENOVIRUS': '腺病毒',
            'CORONAVIRUS': '冠状病毒',
            'CYTOMEGALOVIRUS': '巨细胞病毒',
            'EPSTEIN-BARR VIRUS': 'EB 病毒',
            'HEPATITIS A VIRUS': '甲型肝炎病毒',
            'HEPATITIS B VIRUS': '乙型肝炎病毒',
            'HEPATITIS C VIRUS': '丙型肝炎病毒',
            'HUMAN IMMUNODEFICIENCY VIRUS': '人类免疫缺陷病毒',
            'HUMAN PAPILLOMAVIRUS': '人乳头瘤病毒',
            'INFLUENZA VIRUS': '流感病毒',
            'MEASLES VIRUS': '麻疹病毒',
            'MUMPS VIRUS': '腮腺炎病毒',
            'PARVOVIRUS B19': '细小病毒 B19',
            'RESPIRATORY SYNCYTIAL VIRUS': '呼吸道合胞病毒',
            'RHINOVIRUS': '鼻病毒',
            'ROTAVIRUS': '轮状病毒',
            'VARICELLA ZOSTER VIRUS': '水痘 - 带状疱疹病毒',
        }
        
        # ========== 解剖位置 (Anatomical Location) ==========
        self.anatomical_terms = {
            # 头部
            'HEAD': '头',
            'SCALP': '头皮',
            'FOREHEAD': '前额',
            'TEMPLE': '颞部',
            'CHEEK': '面颊',
            'JAW': '下颌',
            'CHIN': '下巴',
            'NECK': '颈部',
            
            # 眼部
            'EYE': '眼',
            'LEFT EYE': '左眼',
            'RIGHT EYE': '右眼',
            'BOTH EYES': '双眼',
            'CORNEA': '角膜',
            'LENS': '晶状体',
            'RETINA': '视网膜',
            'CONJUNCTIVA': '结膜',
            
            # 耳部
            'EAR': '耳',
            'LEFT EAR': '左耳',
            'RIGHT EAR': '右耳',
            'EXTERNAL EAR': '外耳',
            'MIDDLE EAR': '中耳',
            'INNER EAR': '内耳',
            'EARLOBE': '耳垂',
            
            # 鼻部
            'NOSE': '鼻',
            'NASAL CAVITY': '鼻腔',
            'NASAL SEPTUM': '鼻中隔',
            'NOSTRIL': '鼻孔',
            'LEFT NOSTRIL': '左鼻孔',
            'RIGHT NOSTRIL': '右鼻孔',
            
            # 口部
            'MOUTH': '口',
            'LIP': '唇',
            'UPPER LIP': '上唇',
            'LOWER LIP': '下唇',
            'TONGUE': '舌',
            'TONGUE DORSUM': '舌背',
            'TONGUE VENTRAL': '舌腹',
            'TONGUE LATERAL': '舌缘',
            'PALATE': '腭',
            'HARD PALATE': '硬腭',
            'SOFT PALATE': '软腭',
            'GUM': '牙龈',
            'TEETH': '牙齿',
            'THROAT': '咽喉',
            'PHARYNX': '咽',
            'LARYNX': '喉',
            'TONSIL': '扁桃体',
            'LEFT TONSIL': '左扁桃体',
            'RIGHT TONSIL': '右扁桃体',
            
            # 胸部
            'CHEST': '胸部',
            'THORAX': '胸腔',
            'ANTERIOR CHEST': '前胸',
            'POSTERIOR CHEST': '后背',
            'LEFT CHEST': '左胸',
            'RIGHT CHEST': '右胸',
            'BREAST': '乳房',
            'LEFT BREAST': '左乳房',
            'RIGHT BREAST': '右乳房',
            'AREOLA': '乳晕',
            'NIPPLE': '乳头',
            'AXILLA': '腋窝',
            'LEFT AXILLA': '左腋窝',
            'RIGHT AXILLA': '右腋窝',
            'CLAVICLE': '锁骨',
            'STERNUM': '胸骨',
            'RIB': '肋骨',
            'RIB CAGE': '肋骨',
            'INTERCOSTAL SPACE': '肋间隙',
            
            # 背部
            'BACK': '背部',
            'UPPER BACK': '上背部',
            'LOWER BACK': '下背部',
            'SPINE': '脊柱',
            'CERVICAL SPINE': '颈椎',
            'THORACIC SPINE': '胸椎',
            'LUMBAR SPINE': '腰椎',
            'SACRAL SPINE': '骶椎',
            
            # 腹部
            'ABDOMEN': '腹部',
            'UPPER ABDOMEN': '上腹部',
            'LOWER ABDOMEN': '下腹部',
            'LEFT ABDOMEN': '左腹部',
            'RIGHT ABDOMEN': '右腹部',
            'PERIUMBILICAL': '脐周',
            'UMBILICUS': '脐',
            'FLANK': '胁腹部',
            'LEFT FLANK': '左胁腹',
            'RIGHT FLANK': '右胁腹',
            
            # 盆腔
            'PELVIS': '盆腔',
            'GROIN': '腹股沟',
            'LEFT GROIN': '左腹股沟',
            'RIGHT GROIN': '右腹股沟',
            'PERINEUM': '会阴',
            
            # 上肢
            'UPPER LIMB': '上肢',
            'ARM': '臂',
            'LEFT ARM': '左臂',
            'RIGHT ARM': '右臂',
            'FOREARM': '前臂',
            'LEFT FOREARM': '左前臂',
            'RIGHT FOREARM': '右前臂',
            'WRIST': '腕',
            'LEFT WRIST': '左腕',
            'RIGHT WRIST': '右腕',
            'HAND': '手',
            'LEFT HAND': '左手',
            'RIGHT HAND': '右手',
            'PALM': '手掌',
            'DORSUM OF HAND': '手背',
            'FINGER': '手指',
            'THUMB': '拇指',
            'INDEX FINGER': '食指',
            'MIDDLE FINGER': '中指',
            'RING FINGER': '无名指',
            'LITTLE FINGER': '小指',
            'LEFT THUMB': '左拇指',
            'RIGHT THUMB': '右拇指',
            
            # 下肢
            'LOWER LIMB': '下肢',
            'LEG': '腿',
            'LEFT LEG': '左腿',
            'RIGHT LEG': '右腿',
            'THIGH': '大腿',
            'LEFT THIGH': '左大腿',
            'RIGHT THIGH': '右大腿',
            'KNEE': '膝',
            'LEFT KNEE': '左膝',
            'RIGHT KNEE': '右膝',
            'SHIN': '胫部',
            'CALF': '小腿肚',
            'ANKLE': '踝',
            'LEFT ANKLE': '左踝',
            'RIGHT ANKLE': '右踝',
            'FOOT': '足',
            'LEFT FOOT': '左足',
            'RIGHT FOOT': '右足',
            'SOLE': '足底',
            'DORSUM OF FOOT': '足背',
            'TOE': '脚趾',
            'GREAT TOE': '大脚趾',
            'HEEL': '足跟',
            
            # 内脏
            'LUNG': '肺',
            'LEFT LUNG': '左肺',
            'RIGHT LUNG': '右肺',
            'HEART': '心脏',
            'LIVER': '肝',
            'GALLBLADDER': '胆囊',
            'STOMACH': '胃',
            'PANCREAS': '胰腺',
            'SPLEEN': '脾',
            'KIDNEY': '肾',
            'LEFT KIDNEY': '左肾',
            'RIGHT KIDNEY': '右肾',
            'URINARY BLADDER': '膀胱',
            'INTESTINE': '肠',
            'SMALL INTESTINE': '小肠',
            'LARGE INTESTINE': '大肠',
            'COLON': '结肠',
            'RECTUM': '直肠',
            'APPENDIX': '阑尾',
        }
        
        # ========== PK 单位 (PK Units) ==========
        self.pk_unit_terms = {
            'NG/M L': '纳克/毫升',
            'NG/ML': '纳克/毫升',
            'UG/ML': '微克/毫升',
            'MG/ML': '毫克/毫升',
            'NG/L': '纳克/升',
            'UG/L': '微克/升',
            'MG/L': '毫克/升',
            'NMOL/L': '纳摩尔/升',
            'UMOL/L': '微摩尔/升',
            'MMOL/L': '毫摩尔/升',
            'PMOL/L': '皮摩尔/升',
            'FMOL/L': '飞摩尔/升',
            'NG/M': '纳克/米',
            'UG/M': '微克/米',
            'MG/M': '毫克/米',
            'NMOL/M': '纳摩尔/米',
            'UMOL/M': '微摩尔/米',
            'MMOL/M': '毫摩尔/米',
            'H': '小时',
            'HR': '小时',
            'HRS': '小时',
            'MIN': '分钟',
            'MINUTES': '分钟',
            'SEC': '秒',
            'SECONDS': '秒',
            'DAYS': '天',
            'WEEKS': '周',
            'MONTHS': '月',
            'YEARS': '年',
            'NG.ML/H': '纳克.毫升/小时',
            'UG.ML/H': '微克.毫升/小时',
            'MG.ML/H': '毫克.毫升/小时',
            'NMOL.L/H': '纳摩尔.升/小时',
            'UMOL.L/H': '微摩尔.升/小时',
            'MMOL.L/H': '毫摩尔.升/小时',
            'NG.H/ML': '纳克.小时/毫升',
            'UG.H/ML': '微克.小时/毫升',
            'MG.H/ML': '毫克.小时/毫升',
            'NG.HR/ML': '纳克.小时/毫升',
            'UG.HR/ML': '微克.小时/毫升',
            'MG.HR/ML': '毫克.小时/毫升',
        }
        
        # ========== 方法 (Method) ==========
        self.method_terms = {
            'BLOOD DRAW': '采血',
            'VENIPUNCTURE': '静脉穿刺',
            'CAPILLARY PUNCTURE': '毛细血管穿刺',
            'ARTERIAL PUNCTURE': '动脉穿刺',
            'CENTRIFUGATION': '离心',
            'FILTRATION': '过滤',
            'CHROMATOGRAPHY': '色谱法',
            'HPLC': '高效液相色谱',
            'LC-MS': '液相色谱 - 质谱联用',
            'GC-MS': '气相色谱 - 质谱联用',
            'MASS SPECTROMETRY': '质谱法',
            'SPECTROPHOTOMETRY': '分光光度法',
            'ELISA': '酶联免疫吸附测定',
            'RIA': '放射免疫测定',
            'PCR': '聚合酶链反应',
            'REAL-TIME PCR': '实时聚合酶链反应',
            'WESTERN BLOTTING': 'Western 印迹',
            'NORTHERN BLOTTING': 'Northern 印迹',
            'SOUTHERN BLOTTING': 'Southern 印迹',
            'FLOW CYTOMETRY': '流式细胞术',
            'IMMUNOHISTOCHEMISTRY': '免疫组化',
            'IMMUNOFLUORESCENCE': '免疫荧光',
            'MICROSCOPY': '显微镜检查',
            'LIGHT MICROSCOPY': '光学显微镜',
            'ELECTRON MICROSCOPY': '电子显微镜',
            'FLUORESCENCE MICROSCOPY': '荧光显微镜',
            'CONFOCAL MICROSCOPY': '共聚焦显微镜',
        }
        
        # ========== 剂型 (Dosage Form) ==========
        self.dosage_form_terms = {
            'TABLET': '片剂',
            'CAPSULE': '胶囊',
            'INJECTION': '注射液',
            'SyrUP': '糖浆',
            'SUSPENSION': '混悬剂',
            'EMULSION': '乳剂',
            'CREAM': '乳膏',
            'OINTMENT': '软膏',
            'GEL': '凝胶',
            'LOTION': '洗剂',
            'SOLUTION': '溶液',
            'DROP': '滴剂',
            'EYEDROP': '眼药水',
            'EARDROP': '滴耳剂',
            'NASAL DROP': '滴鼻剂',
            'INHALER': '吸入器',
            'NEBULIZER': '雾化器',
            'SUPPOSITORY': '栓剂',
            'PATCH': '贴剂',
            'TRANSDERMAL SYSTEM': '透皮给药系统',
            'IMPLANT': '植入剂',
            'POWDERS': '散剂',
            'GRANULES': '颗粒剂',
            'EFFERVESCENT TABLET': '泡腾片',
            'CHewABLE TABLET': '咀嚼片',
            'DISPERSIBLE TABLET': '分散片',
            'SUSTAINED-RELEASE TABLET': '缓释片',
            'CONTROLLED-RELEASE TABLET': '控释片',
            'ENTERIC-COATED TABLET': '肠溶片',
            'SOFT CAPSULE': '软胶囊',
            'HARD CAPSULE': '硬胶囊',
            'LIQUID FILL CAPSULE': '液体填充胶囊',
            'INFUSION': '输注液',
            'IV INFUSION': '静脉输注液',
            'IM INJECTION': '肌内注射液',
            'SC INJECTION': '皮下注射液',
            'IV INJECTION': '静脉注射液',
            'INTRATHECAL INJECTION': '鞘内注射液',
            'INTRAARTICULAR INJECTION': '关节腔内注射液',
        }
        
        # ========== 通用医学词汇 ==========
        self.common_medical_terms = {
            'NORMAL': '正常',
            'ABNORMAL': '异常',
            'POSITIVE': '阳性',
            'NEGATIVE': '阴性',
            'INCREASED': '增加',
            'DECREASED': '减少',
            'ELEVATED': '升高',
            'LOW': '低',
            'HIGH': '高',
            'MODERATE': '中度',
            'MILD': '轻度',
            'SEVERE': '重度',
            'CRITICAL': '危急',
            'STABLE': '稳定',
            'IMPROVED': '改善',
            'WORSENED': '恶化',
            'RESOLVED': '缓解',
            'PERSISTENT': '持续',
            'RECURRENT': '复发',
            'ACUTE': '急性',
            'CHRONIC': '慢性',
            'SUBACUTE': '亚急性',
            'PREMATURE': '早产',
            'TERM': '足月',
            'POSTERIOR': '后',
            'ANTERIOR': '前',
            'SUPERIOR': '上',
            'INFERIOR': '下',
            'LATERAL': '外侧',
            'MEDIAL': '内侧',
            'PROXIMAL': '近端',
            'DISTAL': '远端',
            'DORSAL': '背侧',
            'VENTRAL': '腹侧',
            'CERVICAL': '颈',
            'THORACIC': '胸',
            'LUMBAR': '腰',
            'SACRAL': '骶',
            'COCCYGEAL': '尾',
        }
    
    def translate(self, term, codelist_name=None):
        """翻译术语"""
        if not term:
            return None
        
        term_upper = term.upper().strip()
        
        # 根据 codelist_name 选择翻译策略
        if codelist_name:
            if 'Microorganism' in codelist_name:
                # 先查微生物专用词典
                if term_upper in self.microorganism_terms:
                    return self.microorganism_terms[term_upper]
                # 未找到时返回原术语
                return term
            elif 'Anatomical Location' in codelist_name:
                if term_upper in self.anatomical_terms:
                    return self.anatomical_terms[term_upper]
                return term
            elif 'PK Unit' in codelist_name or 'PK Units' in codelist_name:
                if term_upper in self.pk_unit_terms:
                    return self.pk_unit_terms[term_upper]
                return term
            elif 'Method' in codelist_name:
                if term_upper in self.method_terms:
                    return self.method_terms[term_upper]
                return term
            elif 'Dosage Form' in codelist_name:
                if term_upper in self.dosage_form_terms:
                    return self.dosage_form_terms[term_upper]
                return term
        
        # 通用查找策略
        if term_upper in self.microorganism_terms:
            return self.microorganism_terms[term_upper]
        if term_upper in self.anatomical_terms:
            return self.anatomical_terms[term_upper]
        if term_upper in self.pk_unit_terms:
            return self.pk_unit_terms[term_upper]
        if term_upper in self.method_terms:
            return self.method_terms[term_upper]
        if term_upper in self.dosage_form_terms:
            return self.dosage_form_terms[term_upper]
        if term_upper in self.common_medical_terms:
            return self.common_medical_terms[term_upper]
        
        # 未找到翻译时返回原术语
        return term

# 测试
if __name__ == '__main__':
    translator = ExtendedMedicalTranslator()
    
    test_cases = [
        ('ESCHERICHIA COLI', 'Microorganism'),
        ('HEAD', 'Anatomical Location'),
        ('NG/ML', 'PK Units of Measure'),
        ('HPLC', 'Method'),
        ('TABLET', 'Dosage Form'),
    ]
    
    for term, category in test_cases:
        result = translator.translate(term, category)
        print(f"{term:30} [{category:30}] -> {result}")
