# Generated by Django 5.1.15 on 2026-03-10 06:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        ("trials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMonitoringVisit",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("SSV", "Site Selection Visit"),
                            ("SIV", "Site Initiation Visit"),
                            ("RMV", "Routine Monitoring Visit"),
                            ("COV", "Close-out Visit"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("REPORT_DRAFT", "Report Draft"),
                            ("REPORT_FINAL", "Report Finalized"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("planned_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                (
                    "report_content",
                    models.TextField(blank=True, help_text="Detailed visit report"),
                ),
                ("follow_up_items", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trials.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical monitoring visit",
                "verbose_name_plural": "historical monitoring visits",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProtocolDeviation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField()),
                ("date_occurred", models.DateField()),
                ("date_identified", models.DateField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MAJOR", "Major"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MINOR",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESOLVED", "Resolved"),
                            ("CAPA_REQUIRED", "CAPA Required"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trials.site",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="subjects.subject",
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trials.trial",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical protocol deviation",
                "verbose_name_plural": "historical protocol deviations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MonitoringVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("SSV", "Site Selection Visit"),
                            ("SIV", "Site Initiation Visit"),
                            ("RMV", "Routine Monitoring Visit"),
                            ("COV", "Close-out Visit"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("REPORT_DRAFT", "Report Draft"),
                            ("REPORT_FINAL", "Report Finalized"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("planned_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                (
                    "report_content",
                    models.TextField(blank=True, help_text="Detailed visit report"),
                ),
                ("follow_up_items", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_visits",
                        to="trials.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProtocolDeviation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date_occurred", models.DateField()),
                ("date_identified", models.DateField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MAJOR", "Major"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MINOR",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESOLVED", "Resolved"),
                            ("CAPA_REQUIRED", "CAPA Required"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_deviations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deviations",
                        to="trials.site",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deviations",
                        to="subjects.subject",
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deviations",
                        to="trials.trial",
                    ),
                ),
            ],
        ),
    ]
