"""
Excel (.xlsx) 文档导出模块 (美化版)
Spreadsheet Exporter Module

支持:
- Meta 分析结果导出
- 经费预算表导出
- 期刊数据库导出
- 生存分析数据导出
"""

import os
from typing import Dict, List, Any, Optional
from datetime import datetime

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
    from openpyxl.chart import BarChart, LineChart, Reference, PieChart
    from openpyxl.formatting.rule import DataBarRule, ColorScaleRule, IconSetRule
    from openpyxl.worksheet.datavalidation import DataValidation
    HAS_OPENPYXL = True
except ImportError:
    HAS_OPENPYXL = False

from .styles import ExcelColors, BRAND_NAME


class BaseSpreadsheetExporter:
    """Excel 导出基类 - 美化版"""

    def __init__(self):
        if not HAS_OPENPYXL:
            raise ImportError("openpyxl is required. Install: pip install openpyxl")
        self.wb = Workbook()
        self.ws = self.wb.active

    def _setup_header_style(self, row: int, cols: int):
        """设置专业表头样式（医学蓝主题）"""
        header_fill = PatternFill(
            start_color=ExcelColors.PRIMARY,
            end_color=ExcelColors.PRIMARY,
            fill_type="solid"
        )
        header_font = Font(
            bold=True,
            color=ExcelColors.HEADER_TEXT,
            size=11,
            name="微软雅黑"
        )
        header_align = Alignment(
            horizontal="center",
            vertical="center",
            wrap_text=True
        )
        thin_border = Border(
            bottom=Side(style="medium", color=ExcelColors.PRIMARY_DK)
        )

        for col in range(1, cols + 1):
            cell = self.ws.cell(row=row, column=col)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = header_align
            cell.border = thin_border

    def _apply_zebra_striping(self, start_row: int, end_row: int, cols: int):
        """应用斑马纹（浅蓝交替）"""
        fill_even = PatternFill(
            start_color=ExcelColors.ZEBRA_EVEN,
            end_color=ExcelColors.ZEBRA_EVEN,
            fill_type="solid"
        )
        fill_odd = PatternFill(
            start_color=ExcelColors.ZEBRA_ODD,
            end_color=ExcelColors.ZEBRA_ODD,
            fill_type="solid"
        )
        thin_border = Border(
            left=Side(style="thin", color=ExcelColors.BORDER),
            right=Side(style="thin", color=ExcelColors.BORDER),
            top=Side(style="thin", color=ExcelColors.BORDER),
            bottom=Side(style="thin", color=ExcelColors.BORDER),
        )

        for row in range(start_row, end_row + 1):
            fill = fill_even if (row - start_row) % 2 == 0 else fill_odd
            for col in range(1, cols + 1):
                cell = self.ws.cell(row=row, column=col)
                cell.fill = fill
                cell.border = thin_border
                cell.alignment = Alignment(vertical="center")

    def _apply_data_bars(self, col_letter: str, start_row: int, end_row: int,
                         color: str = "1E5AA8"):
        """为列添加数据条条件格式"""
        rule = DataBarRule(
            start_type='min', end_type='max',
            color=color,
            showValue=True, minLength=None, maxLength=None
        )
        self.ws.conditional_formatting.add(
            f'{col_letter}{start_row}:{col_letter}{end_row}', rule
        )

    def _apply_color_scale(self, col_letter: str, start_row: int, end_row: int):
        """为列添加色阶条件格式（绿-白-红）"""
        rule = ColorScaleRule(
            start_type='min', start_color='C0392B',
            mid_type='percentile', mid_value=50, mid_color='FFFFFF',
            end_type='max', end_color='2E8B57'
        )
        self.ws.conditional_formatting.add(
            f'{col_letter}{start_row}:{col_letter}{end_row}', rule
        )

    def _add_title_row(self, title_text: str, merge_range: str,
                       height: int = 35):
        """添加统一标题行"""
        self.ws.merge_cells(merge_range)
        title_cell = self.ws[merge_range.split(':')[0]]
        title_cell.value = title_text
        title_cell.font = Font(
            bold=True, size=16, color=ExcelColors.PRIMARY_DK,
            name="微软雅黑"
        )
        title_cell.alignment = Alignment(
            horizontal="center", vertical="center"
        )
        row_num = int(''.join(filter(str.isdigit, merge_range.split(':')[0])))
        self.ws.row_dimensions[row_num].height = height

    def _add_brand_footer(self, row: int):
        """添加品牌页脚"""
        cell = self.ws.cell(row=row, column=1)
        cell.value = f"Generated by {BRAND_NAME}  |  {datetime.now().strftime('%Y-%m-%d')}"
        cell.font = Font(size=9, color=ExcelColors.TEXT_LT, italic=True)

    def _auto_column_width(self, min_width: int = 10, max_width: int = 50):
        """自动调整列宽"""
        for column in self.ws.columns:
            max_length = 0
            column_letter = get_column_letter(column[0].column)
            for cell in column:
                try:
                    if cell.value:
                        max_length = max(max_length, len(str(cell.value)))
                except:
                    pass
            adjusted_width = min(max(min_width, max_length + 2), max_width)
            self.ws.column_dimensions[column_letter].width = adjusted_width

    def _freeze_header(self, freeze_row: int = 2):
        """冻结表头行"""
        self.ws.freeze_panes = f"A{freeze_row}"

    def _add_auto_filter(self, start_row: int, end_row: int, cols: int):
        """添加自动筛选"""
        start_col = get_column_letter(1)
        end_col = get_column_letter(cols)
        self.ws.auto_filter.ref = f"{start_col}{start_row}:{end_col}{end_row}"

    def save(self, file_path: str):
        """保存工作簿"""
        os.makedirs(os.path.dirname(file_path) or '.', exist_ok=True)
        self.wb.save(file_path)
        return file_path


class MetaAnalysisExporter(BaseSpreadsheetExporter):
    """Meta 分析结果导出器 - 美化版"""

    def export_meta_analysis(self, result: Dict[str, Any], file_path: str) -> str:
        """
        将 Meta 分析结果导出为 Excel

        Args:
            result: MetaAnalysisResult 的字典表示
            file_path: 输出路径
        """
        self.ws.title = "Meta Analysis"

        # 标题
        self._add_title_row("Meta-Analysis Results", "A1:F1", height=35)

        # 研究数据
        row = 3
        self.ws.cell(row=row, column=1, value="Study Data")
        self.ws.cell(row=row, column=1).font = Font(
            bold=True, size=12, color=ExcelColors.PRIMARY_DK, name="微软雅黑"
        )
        row += 1

        headers = ["Study", "Group A Events", "Group A Total", "Group B Events", "Group B Total", "Effect Size"]
        for i, h in enumerate(headers, 1):
            self.ws.cell(row=row, column=i, value=h)
        self._setup_header_style(row, len(headers))

        studies = result.get("studies", [])
        start_data_row = row + 1
        for i, study in enumerate(studies):
            r = row + 1 + i
            self.ws.cell(row=r, column=1, value=study.get("name", f"Study {i+1}"))
            self.ws.cell(row=r, column=2, value=study.get("a_events", 0))
            self.ws.cell(row=r, column=3, value=study.get("a_total", 0))
            self.ws.cell(row=r, column=4, value=study.get("b_events", 0))
            self.ws.cell(row=r, column=5, value=study.get("b_total", 0))
            self.ws.cell(row=r, column=6, value=round(study.get("effect_size", 0), 3))

        end_data_row = row + len(studies)
        self._apply_zebra_striping(start_data_row, end_data_row, len(headers))

        # 为 Effect Size 列添加数据条
        self._apply_data_bars('F', start_data_row, end_data_row)

        # 汇总统计
        row = end_data_row + 2
        self.ws.cell(row=row, column=1, value="Summary Statistics")
        self.ws.cell(row=row, column=1).font = Font(
            bold=True, size=12, color=ExcelColors.PRIMARY_DK, name="微软雅黑"
        )
        row += 1

        summary_headers = ["Statistic", "Value"]
        self.ws.cell(row=row, column=1, value=summary_headers[0])
        self.ws.cell(row=row, column=2, value=summary_headers[1])
        self._setup_header_style(row, 2)
        row += 1

        summary_items = [
            ("Pooled Effect Size", result.get("pooled_effect", "N/A")),
            ("95% CI Lower", result.get("ci_lower", "N/A")),
            ("95% CI Upper", result.get("ci_upper", "N/A")),
            ("Heterogeneity I²", result.get("i_squared", "N/A")),
            ("Q Statistic", result.get("q_statistic", "N/A")),
            ("P-value", result.get("p_value", "N/A")),
            ("Model", result.get("model", "Random")),
        ]

        for label, value in summary_items:
            self.ws.cell(row=row, column=1, value=label)
            self.ws.cell(row=row, column=1).font = Font(bold=True, name="微软雅黑")
            self.ws.cell(row=row, column=2, value=value)
            row += 1

        # 冻结表头 + 自动筛选
        self._freeze_header(freeze_row=start_data_row)
        self._add_auto_filter(start_data_row, end_data_row, len(headers))

        # 页脚
        self._add_brand_footer(row + 1)
        self._auto_column_width()
        return self.save(file_path)


class BudgetExporter(BaseSpreadsheetExporter):
    """经费预算表导出器 - 美化版"""

    def export_budget(self, budget_data: Dict[str, Any], file_path: str) -> str:
        """
        将经费预算导出为 Excel

        Args:
            budget_data: 预算数据，包含 items 列表和 total
            file_path: 输出路径
        """
        self.ws.title = "Budget"

        # 标题
        title = budget_data.get("title", "Research Budget")
        self._add_title_row(title, "A1:E1", height=35)

        # 表头
        row = 3
        headers = ["No.", "Budget Item", "Amount (10K CNY)", "Percentage", "Notes"]
        for i, h in enumerate(headers, 1):
            self.ws.cell(row=row, column=i, value=h)
        self._setup_header_style(row, len(headers))

        # 数据
        items = budget_data.get("items", [])
        total = budget_data.get("total", 0)
        start_data_row = row + 1

        for i, item in enumerate(items, 1):
            r = row + i
            amount = item.get("amount", 0)
            pct = f"{amount / total * 100:.1f}%" if total > 0 else "0%"
            self.ws.cell(row=r, column=1, value=i)
            self.ws.cell(row=r, column=2, value=item.get("name", ""))
            self.ws.cell(row=r, column=3, value=round(amount, 2))
            self.ws.cell(row=r, column=4, value=pct)
            self.ws.cell(row=r, column=5, value=item.get("notes", ""))

        end_data_row = row + len(items)
        self._apply_zebra_striping(start_data_row, end_data_row, len(headers))

        # 为金额列添加数据条
        self._apply_data_bars('C', start_data_row, end_data_row)

        # 合计行
        total_row = end_data_row + 1
        total_fill = PatternFill(start_color=ExcelColors.PRIMARY_LT,
                                  end_color=ExcelColors.PRIMARY_LT, fill_type="solid")
        for c in range(1, len(headers) + 1):
            cell = self.ws.cell(row=total_row, column=c)
            cell.fill = total_fill
            cell.font = Font(bold=True, name="微软雅黑")
            cell.border = Border(
                top=Side(style="medium", color=ExcelColors.PRIMARY)
            )
        self.ws.cell(row=total_row, column=2, value="Total")
        self.ws.cell(row=total_row, column=3, value=round(total, 2))
        self.ws.cell(row=total_row, column=4, value="100%")

        # 添加饼图（预算占比）
        if len(items) > 0:
            pie = PieChart()
            pie.title = "Budget Distribution"
            pie.style = 10
            labels = Reference(self.ws, min_col=2, min_row=start_data_row, max_row=end_data_row)
            data = Reference(self.ws, min_col=3, min_row=row, max_row=end_data_row)
            pie.add_data(data, titles_from_data=True)
            pie.set_categories(labels)
            pie.width = 12
            pie.height = 8
            self.ws.add_chart(pie, f"G{row}")

        # 冻结表头 + 自动筛选 + 页脚
        self._freeze_header(freeze_row=start_data_row)
        self._add_auto_filter(start_data_row, end_data_row, len(headers))
        self._add_brand_footer(total_row + 3)

        self._auto_column_width()
        return self.save(file_path)


class JournalDatabaseExporter(BaseSpreadsheetExporter):
    """期刊数据库导出器 - 美化版"""

    def export_journals(self, journals: List[Dict[str, Any]],
                        file_path: str) -> str:
        """
        将期刊数据库导出为 Excel

        Args:
            journals: 期刊列表
            file_path: 输出路径
        """
        self.ws.title = "Journals"

        # 标题
        self._add_title_row("Medical Journal Database", "A1:H1", height=35)

        # 表头
        row = 3
        headers = ["No.", "Journal Name", "Impact Factor", "JCR Quartile",
                   "CAS Quartile", "Field", "OA Policy", "Review Period"]
        for i, h in enumerate(headers, 1):
            self.ws.cell(row=row, column=i, value=h)
        self._setup_header_style(row, len(headers))

        start_data_row = row + 1
        for i, journal in enumerate(journals, 1):
            r = row + i
            self.ws.cell(row=r, column=1, value=i)
            self.ws.cell(row=r, column=2, value=journal.get("name", ""))
            self.ws.cell(row=r, column=3, value=journal.get("impact_factor", ""))
            self.ws.cell(row=r, column=4, value=journal.get("jcr_quartile", ""))
            self.ws.cell(row=r, column=5, value=journal.get("cas_quartile", ""))
            self.ws.cell(row=r, column=6, value=journal.get("field", ""))
            self.ws.cell(row=r, column=7, value=journal.get("oa_policy", ""))
            self.ws.cell(row=r, column=8, value=journal.get("review_period", ""))

        end_data_row = row + len(journals)
        self._apply_zebra_striping(start_data_row, end_data_row, len(headers))

        # 为 IF 列添加色阶（高 IF 绿色，低 IF 红色）
        self._apply_color_scale('C', start_data_row, end_data_row)

        # 冻结表头 + 自动筛选 + 页脚
        self._freeze_header(freeze_row=start_data_row)
        self._add_auto_filter(start_data_row, end_data_row, len(headers))
        self._add_brand_footer(end_data_row + 2)

        self._auto_column_width()
        return self.save(file_path)


class SurvivalDataExporter(BaseSpreadsheetExporter):
    """生存分析数据导出器 - 美化版"""

    def export_survival_data(self, records: List[Dict[str, Any]],
                             file_path: str) -> str:
        """
        将生存分析数据导出为 Excel

        Args:
            records: 生存记录列表
            file_path: 输出路径
        """
        self.ws.title = "Survival Data"

        # 标题
        self._add_title_row("Survival Analysis Data", "A1:F1", height=35)

        # 表头
        row = 3
        headers = ["Patient ID", "Time (months)", "Event (0=censored, 1=event)",
                   "Group", "Age", "Stage"]
        for i, h in enumerate(headers, 1):
            self.ws.cell(row=row, column=i, value=h)
        self._setup_header_style(row, len(headers))

        start_data_row = row + 1
        for i, record in enumerate(records):
            r = row + 1 + i
            self.ws.cell(row=r, column=1, value=record.get("patient_id", ""))
            self.ws.cell(row=r, column=2, value=record.get("time", 0))
            self.ws.cell(row=r, column=3, value=record.get("event", 0))
            self.ws.cell(row=r, column=4, value=record.get("group", ""))
            self.ws.cell(row=r, column=5, value=record.get("age", ""))
            self.ws.cell(row=r, column=6, value=record.get("stage", ""))

        end_data_row = row + len(records)
        self._apply_zebra_striping(start_data_row, end_data_row, len(headers))

        # 为 Time 列添加数据条
        self._apply_data_bars('B', start_data_row, end_data_row)

        # 冻结表头 + 自动筛选 + 页脚
        self._freeze_header(freeze_row=start_data_row)
        self._add_auto_filter(start_data_row, end_data_row, len(headers))
        self._add_brand_footer(end_data_row + 2)

        self._auto_column_width()
        return self.save(file_path)
